export const ADD_REVIEW = "ADD_REVIEW";
export const SET_CURRENT_REVIEW_EMAIL = "SET_CURRENT_REVIEW_EMAIL";
export const SET_CURRENT_REVIEW_TITLE = "SET_CURRENT_REVIEW_TITLE";
export const SET_CURRENT_REVIEW_MESSAGE = "SET_CURRENT_REVIEW_MESSAGE";
export const INIT_REVIEWS = 'INIT_REVIEWS';
export const INIT_POSTS = 'INIT_POSTS';