export const REGISTER_FORM_AT = {
    INIT: "REGISTER_FORM_INIT",
    CHANGE_FIELD: "REGISTER_FORM_CHANGE_FIELD",
    SUBMIT_START: "REGISTER_FORM_SUBMIT_START",
    SUBMIT_SUCCESS: "REGISTER_FORM_SUBMIT_SUCCESS",
    SUBMIT_FAIL: "REGISTER_FORM_SUBMIT_FAIL"
};
