import img0 from './images/writing-tool.svg';
import img1 from './images/reading.svg';
import img2 from './images/carpenter.svg';
import img3 from './images/planet-earth.svg';
import img4 from './images/calculating.svg';
import img5 from './images/singing.svg';
import img6 from './images/paint.svg';
import img7 from './images/kremlin.svg';
import img8 from './images/fitness.svg';
import img9 from './images/house.svg';
import img10 from './images/church.svg';
import img11 from './images/foreign-language.svg';
import img12 from './images/overpopulation.svg';
import img13 from './images/history.svg';
import img14 from './images/history_writing.svg';
import img15 from './images/library.svg';
import img16 from './images/life-jacket.svg';
import img17 from './images/project-management.svg';
import img18 from './images/world-map.svg';
import img19 from './images/biology.svg';
import img20 from './images/computer.svg';
import img21 from './images/communities.svg';
import img22 from './images/divider.svg';
import img23 from './images/algebra.svg';
import img24 from './images/shapes.svg';
import img25 from './images/relativity.svg';
import img26 from './images/chemistry.svg';
import img27 from './images/economic.svg';
import img28 from './images/justice.svg';
import img29 from './images/yin-yang.svg';
import img30 from './images/eco.svg';
import img31 from './images/astronomy.svg';

let images = [img0, img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12, img13, img14, img15, img16, img17, img18, img19, img20, img21, img22, img23, img24, img25, img26, img27, img28, img29, img30, img31];

export default images;