const data = [
    {id: 0, title: "Чистописание", href: "calligraphy"},
    {id: 1, title: "Чтение", href: "reading"},
    {id: 2, title: "Труд", href: "work"},
    {id: 3, title: "Природоведение", href: "natural_science"},
    {id: 4, title: "Математика", href: "mathematics"},
    {id: 5, title: "Музыка (Пение)", href: "music_(singing)"},
    {id: 6, title: "Изобразительное искусство (Рисование)", href: "fine_arts_(drawing)"},
    {id: 7, title: "Русский язык", href: "russian_language"},
    {id: 8, title: "Физкультура", href: "physical_education"},
    {id: 9, title: "Родной язык", href: "native_language"},
    {id: 10, title: "Основы религиозных культур и светской этики", href: "foundations_of_religious_cultures_and_secular_ethics"},
    {id: 11, title: "Иностранный язык", href: "foreign_language"},
    {id: 12, title: "Граждановедение", href: "citizenship"},
    {id: 13, title: "Краеведение", href: "local_history"},
    {id: 14, title: "История", href: "history"},
    {id: 15, title: "Литература", href: "literature"},
    {id: 16, title: "Основы безопасности жизнедеятельности (ОБЖ)", href: "fundamentals_of_life_safety_(obzh)"},
    {id: 17, title: "Технология", href: "technology"},
    {id: 18, title: "География", href: "geography"},
    {id: 19, title: "Биология", href: "biology"},
    {id: 20, title: "Информатика", href: "computer_science"},
    {id: 21, title: "Обществознание", href: "social_science"},
    {id: 22, title: "Черчение", href: "drawing"},
    {id: 23, title: "Алгебра", href: "algebra"},
    {id: 24, title: "Геометрия", href: "geometry"},
    {id: 25, title: "Физика", href: "physics"},
    {id: 26, title: "Химия", href: "chemistry"},
    {id: 27, title: "Основы экономики", href: "fundamentals_of_economics"},
    {id: 28, title: "Правоведение", href: "jurisprudence"},
    {id: 29, title: "Философия", href: "philosophy"},
    {id: 30, title: "Экология", href: "ecology"},
    {id: 31, title: "Астрономия", href: "astronomy"}
];

export default data;